plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' version '2.0.21'
    id 'com.google.gms.google-services'
}

android {
    namespace 'com.vieespoir.marketing'
    compileSdk 35

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    defaultConfig {
        applicationId 'com.vieespoir.marketing'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.3.0')

    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-analytics'
}