plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' version '2.0.21'
}

android {
    namespace 'com.vieespoir.marketing'
    compileSdk 35

    defaultConfig {
        applicationId 'com.vieespoir.marketing'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }
}